server:
  port: 8050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
logging:
  level:
    org:
      springframework:
        security: TRACE
kafka:
  bootstrapAddress: kafka:9092